import Layout from '@/layouts/Layout'
import '@/styles/globals.css'
import Head from 'next/head'

const App = ({ Component, pageProps }) => {

  return (
    <>
      <Head>
        <title>Auto Promo PH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}

export default App