import '@/styles/globals.css'
import theme from '@/utils/theme'
import { ThemeProvider } from '@mui/material'
import { AuthContextProvider } from '@/context/AuthContext'
import { ListingContextProvider } from '@/context/ListingContext'
import Head from 'next/head'
import { InquiriesContextProvider } from '@/context/InquiriesContext'

const App = ({ Component, pageProps }) => {

  return (
    <>
      <Head>
        <title>Auto Promo PH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthContextProvider>
        <ListingContextProvider>
          <InquiriesContextProvider>
            <ThemeProvider theme={theme}>
              <Component {...pageProps} />
            </ThemeProvider>
          </InquiriesContextProvider>
        </ListingContextProvider>
      </AuthContextProvider>
    </>
  )
}

export default App